export class Alimento {
    constructor(private codigo_alimento: number,
        private descripcion_alimento: string,
        private tipo_alimento: number,
        private medida_casera: string,
        private medida_casera_unidad: string,
        private medida_real: number,
        private medida_real_unidad: string,
        private hidratos_carbono: number,
        private unidad_medida_hidratos_carbono: string,
        private proteina: number,
        private unidad_medida_proteina: string,
        private grasa: number,
        private unidad_medida_grasa: string,
        private sodio: number,
        private unidad_medida_sodio: string,
        private potasio: number,
        private unidad_medida_potasio: string,
        private fosforo: number,
        private unidad_medida_fosforo: string,
        private calcio: number,
        private unidad_medida_calcio: string,
        private hierro: number,
        private unidad_medida_hierro: string,
        private colesterol: number,
        private unidad_medida_colesterol: string,
        private purinas: number,
        private unidad_medida_purinas: string,
        private fibra: number,
        private unidad_medida_fibra: string,
        private agua: number,
        private unidad_medida_agua: string,
        private calorias: number) {

    }
}
