export class Paciente {
    constructor(private codigo_paciente: any,
        private nombre: string,
        private apellido: string,
        private sexo: string,
        private talla: any,
        private estado_civil: string,
        private fecha_nacimiento,
        private peso_actual: number,
        private peso_habitual: number,
        private peso_ajusta: number,
        private peso_saludable: number,
        private porcentaje_peso_ideal: number,
        private imc: number,
        private cia_muneca: number,
        private cia_brazo: number,
        private biotipo: string,
        private antecedente_obesidad: boolean,
        private antecedente_cardiopatias: boolean,
        private antecedente_hta: boolean,
        private antecedente_diabetes: boolean,
        private medicacion: string,
        private diagnostico_medico: string,
        private diagnostico_nutricional: string,
        private laboratorio_glicemia_basal: number,
        private laboratorio_creatinina: number,
        private laboratorio_proteinas_totales: number,
        private laboratorio_urea: number,
        private laboratorio_acido_urico: number,
        private laboratorio_proteinuria: number,
        private laboratorio_albumina: number,
        private laboratorio_triglicerios: number,
        private laboratorio_colesterol_total: number,
        private laboratorio_ldl: number,
        private laboratorio_hdl: number,
        private laboratorio_glucosa: number,
        private laboratorio_hb: number,
        private laboratorio_hematocrito: number,
        private laboratorio_globulos_rojos: number,
        private laboratorio_potasio: number,
        private laboratorio_ci: number,
        private laboratorio_na: number,
        private laboratorio_globulos_blancos: number,
        private laboratorio_hba: number,
        private cia_cintura1: number,
        private cia_cintura2: number) {

    }
}