export class PacienteDetalle {
    constructor(public codigo_paciente: any,
        public nombre: string,
        public apellido: string,
        public sexo: string,
        public talla: any,
        public estado_civil: string,
        public fecha_nacimiento: Date,
        public peso_actual: number,
        public peso_habitual: number,
        public peso_ajusta: number,
        public peso_saludable: number,
        public porcentaje_peso_ideal: number,
        public imc: number,
        public cia_muneca: number,
        public cia_brazo: number,
        public biotipo: string,
        public antecedente_obesidad: boolean,
        public antecedente_cardiopatias: boolean,
        public antecedente_hta: boolean,
        public antecedente_diabetes: boolean,
        public medicacion: string,
        public diagnostico_medico: string,
        public diagnostico_nutricional: string,
        public laboratorio_glicemia_basal: number,
        public laboratorio_creatinina: number,
        public laboratorio_proteinas_totales: number,
        public laboratorio_urea: number,
        public laboratorio_acido_urico: number,
        public laboratorio_proteinuria: number,
        public laboratorio_albumina: number,
        public laboratorio_triglicerios: number,
        public laboratorio_colesterol_total: number,
        public laboratorio_ldl: number,
        public laboratorio_hdl: number,
        public laboratorio_glucosa: number,
        public laboratorio_hb: number,
        public laboratorio_hematocrito: number,
        public laboratorio_globulos_rojos: number,
        public laboratorio_potasio: number,
        public laboratorio_ci: number,
        public laboratorio_na: number,
        public laboratorio_globulos_blancos: number,
        public laboratorio_hba: number,
        public cia_cintura1: number,
        public cia_cintura2: number) {
            
    } 
}